let suggestions = [
    "TOTAN",
    "HEHEHEHE",
    "YES",
    "chicc", 
    "meow",
    "something",
    "random",
    "just testing",
    "dont mind me",
    "lol",
    "sengolda", 
    "coni",
    "hehe",
    "cannibalism",
    "Soviet onion",
    "OINK OINK",
    "Se",
    "SO",
    "S888",
    "smar",
    "st",
    "saaaa",
    "s00",
    "saaaaaaaaaaaaaaaa",
    "smeow"
];